### ISSUE TITLE
Is this available?

### ISSUE THREAD

**Issue by thesammiller** [hibaalkayed/DistPcalTranslate#1]
Hi,

I found your YouTube presentation and your work looks great! I am interested in exploring this project more. Is it available for use? It seems like there are no files currently. Is there anything you can share?

Thanks,
Sam

**Comment by hebaalkayed** [comment]
Hi Sam,

Thank you for reaching out, we moved our work to https://github.com/DistributedPlusCal/DistributedPlusCal/ , the refactor branch has our most recent changes and bug fixes.

Thanks,
Heba
